const CMSImageUrl = process.env.NEXT_PUBLIC_S3_URL;
export const verifiedMarkDesktop = `${CMSImageUrl}/Vector_08257cba8b.png`;
export const verifiedMarkMobile = `${CMSImageUrl}/tick_circle_2b2a2960fb.png`;
export const PercentageLogo = `${CMSImageUrl}/percentage_circle_a83dc10983.png`;
export const InformationIcon = `${CMSImageUrl}/info_circle_c8621412e1.png`;
export const emptyCartImage = `${CMSImageUrl}/empty_cart_4d7d245153.png`;
export const square_tick = `${CMSImageUrl}/tick_square_d44857fb3d.png`;
export const circle_tick = `${CMSImageUrl}/tick_circle_2b2a2960fb.png`;
export const CartTruckImage = `${CMSImageUrl}/truck_tick_3043de6349.png`;
export const CODImage = `${CMSImageUrl}/cashondelivery2x_f14140dfa4.png`;
export const CardPaymentImage = `${CMSImageUrl}/cartpaymentcard_60a881133a.png`;
export const UPIPaymentImage = `${CMSImageUrl}/UP_Ipayment_Card_13861e3063.png`;
export const CloseCircleWarning = `${CMSImageUrl}/close_circle_warning_ba4318124a.png`;
export const TickCircleWarning = `${CMSImageUrl}/tick_circle_Warning_3863d131e6.png`;
export const CalenderIcon = `${CMSImageUrl}/calendar11_9192679bc8.png`;
export const GPSIcon = `${CMSImageUrl}/gps_27ae7a7483.png`;
export const QuantityDropDown = `${CMSImageUrl}/dropdown_6da832960c.png`;
export const FccCrown = "fccCrown"
