---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
    app: {{ include "web.fullname" . }}
spec:
  hosts:
  - {{ .Values.istio.host | quote }}
  gateways:
  - {{ .Values.istio.gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "web.fullname" . }}
        port:
          number: {{ .Values.service.port }}