const CMSImageUrl = process.env.NEXT_PUBLIC_S3_URL
export const STAR_ICON_URL = `${CMSImageUrl}/star_icon_6262adce21.png`
export const TROPHY_ICON_URL = `${CMSImageUrl}/trophy_icon_7c5bbf6efe.png`
export const HEART_FILLED_ICON_URL = `${CMSImageUrl}/wishlist_filled_heart_da662672b7.png`
export const HEART_EMPTY_ICON_URL = `${CMSImageUrl}/wishlist_empty_heart_0cad157633.png`
export const CLOSE_ICON_URL = `${CMSImageUrl}/plp_Close_Icon_7a07dc0a6e.png`
export const TAX_TEXT = "(Inclusive of all taxes)"
export const WISHLIST_IMAGE_URL = `${CMSImageUrl}/Empty_Wishlist_icon_11ef48e0c9.png`
export const SEARCH_NORMAL = `${CMSImageUrl}/search_Icon_0cab05cf1b.png`
export const UNCHECKEDICON = `${CMSImageUrl}/un_Checked_e668b6e294.png`
export const CHECKEDICON = `${CMSImageUrl}/tick_square_black_bd05a481e9.png`
export const ARROWDOWN = `${CMSImageUrl}/arrow_down_icon_c9481daf9b.png`
export const SORT_ARROW = `${CMSImageUrl}/sortplp_cfe520c840.png`
export const DISCOUNT_IMAGE = `${CMSImageUrl}/percentage_circle_a83dc10983.png`
export const Filter_settings = `${CMSImageUrl}/setting_5a63aec473.png`
export const PRODUCT_FALLBACK_URL = `${CMSImageUrl}/Products_Placeholder_0718784858_27f7c693d1.png`
export const THANKS_MESSAGE = "Thank you. You'll be notified once this product is back in stock."
export const OKAY_CTA = "OKAY, GOT IT"