apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-app
  template:
    metadata:
      labels:
        app: sample-node-app
    spec:
      containers:
        - name: node-app
          image: sample-node-app:latest  # Local image built in Minikube
          imagePullPolicy: Never          # Important: don't try to pull from Docker Hub
          ports:
            - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: sample-node-service
spec:
  type: NodePort
  selector:
    app: sample-node-app
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
