name: Deploy Application on VM

on:
  push:
    branches:
      - master   # Trigger workflow on push to master branch

jobs:
  deploy:
    runs-on: self-hosted   # Run on your self-hosted VM runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Node.js App on VM
        run: |
          # Go to app directory
          mkdir -p /home/tech/app
          cd /home/tech/app

          # Sync the latest code (skip git and workflow files)
          rsync -av --delete --exclude='.git' --exclude='.github' $GITHUB_WORKSPACE/ .

          # Stop any running container with the same name
          docker stop sample-node-app || true
          docker rm sample-node-app || true

          # Build Docker image
          docker build -t sample-node-app .

          # Run Docker container
          docker run -d --name sample-node-app -p 3005:3005 sample-node-app

          # Wait a few seconds for container to start
          sleep 5

          # Check if the container is running
          docker ps | grep sample-node-app || (echo "❌ App failed to start!" && exit 1)

          # Optional: Display app logs
          echo "✅ Application Logs:"
          docker logs --tail 20 sample-node-app
