name: Deploy Node App to Minikube

on:
  push:
    branches:
      - minikube-branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Your VM where Minikube runs

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Use Minikube Docker for building
      - name: Set up Minikube Docker
        run: |
          eval $(minikube -p minikube docker-env)
          docker info

      # Step 3: Build Docker image inside Minikube
      - name: Build Docker image
        run: |
          docker build -t sample-node-app:latest .

      # Step 4: Apply Kubernetes manifests
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # Step 5: Check rollout status
      - name: Check rollout
        run: |
          kubectl rollout status deployment/sample-node-app
