name: Deploy Application on VM

on:
  push:
    branches:
      - master   # Trigger workflow on push to master branch

jobs:
  deploy:
    runs-on: self-hosted   # Use your self-hosted runner (the VM itself)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Application on VM
      run: |
        # Create app directory if not exists
        mkdir -p /home/tech/app

        # Copy repository files to app directory
        cp -r * /home/tech/app/

        # Navigate to app directory
        cd /home/tech/app

        # Optional: Install Python dependencies if it is a Python app
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi

        # Start the application (Python example)
        nohup python3 app.py > app.log 2>&1 &
