name: Build & Deploy on Minikube

on:
  push:
    branches:
      - minikube-branch

jobs:
  deploy:
    runs-on: self-hosted   # The VM with Minikube installed

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build and Deploy in Minikube
      run: |
        # 1. Point Docker CLI to Minikube's Docker
        eval $(minikube docker-env)
        docker info

        # 2. Build Docker image inside Minikube
        cd $GITHUB_WORKSPACE
        docker build -t sample-node-app:latest .

        # 3. Delete old pods (optional)
        kubectl delete pod -l app=sample-node-app --ignore-not-found=true --namespace default

        # 4. Apply Kubernetes manifests
        kubectl apply -f k8s/deployment.yaml --namespace default

        # 5. Wait for deployment rollout
        kubectl rollout status deployment/sample-node-app --namespace default

        # 6. Verify pod status
        kubectl get pods -l app=sample-node-app --namespace default
