name: Build & Deploy on Minikube

on:
  push:
    branches:
      - minikube-branch

jobs:
  deploy:
    runs-on: self-hosted   # Your VM with Minikube

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Minikube Docker Environment
      run: |
        # Configure shell to use Minikube Docker daemon
        eval $(minikube docker-env)

    - name: Build Docker Image in Minikube
      run: |
        docker build -t sample-node-app:latest .

    - name: Apply Kubernetes Deployment
      run: |
        # Optional: delete old pods if needed
        kubectl delete pod -l app=sample-node-app --ignore-not-found=true --namespace default

        # Apply deployment manifest
        kubectl apply -f k8s/deployment.yaml --namespace default

    - name: Wait for Deployment Rollout
      run: |
        kubectl rollout status deployment/sample-node-app --namespace default

    - name: Verify Pod is Running
      run: |
        kubectl get pods -l app=sample-node-app --namespace default